const businesses = [
  {id:'puebloastur',name:'Puebloastur Eco Resort',category:'Espacios',zone:'Oriente',place:'Parres · Oriente',symbol:'⌂',summary:'Un resort entre montañas para celebrar una boda con alojamiento y espacios interiores y exteriores.',detail:'Puebloastur presenta espacios para ceremonia, banquete y celebración en un entorno rural junto a la Sierra del Sueve. Consulta las opciones de exclusividad y alojamiento directamente con el equipo.',url:'https://www.puebloastur.com/bodas'},
  {id:'villa-maria',name:'Finca Villa María',category:'Espacios',zone:'Gijón',place:'Gijón',symbol:'✦',summary:'Finca y restaurante para bodas con espacios de celebración en Gijón.',detail:'Finca Villa María presenta propuestas de bodas y eventos en su finca de Gijón. Su web permite conocer el lugar y contactar para una visita.',url:'https://fincavillamariagijon.es/bodas/'},
  {id:'quinta-ynfanzon',name:'La Quinta del Ynfanzón',category:'Espacios',zone:'Gijón',place:'Gijón',symbol:'⌂',summary:'Finca centenaria con salón para bodas, gastronomía y alojamiento rural.',detail:'La Quinta del Ynfanzón reúne finca, salón polivalente y hotel rural a pocos minutos de Gijón. Consulta en su web el formato que mejor se adapta a tu boda.',url:'https://quintadelynfanzon.com/'},
  {id:'deloya-latores',name:'Deloya Latores',category:'Espacios',zone:'Oviedo',place:'Oviedo',symbol:'✧',summary:'Finca singular en Oviedo con espacios interiores y exteriores para celebraciones.',detail:'Deloya Latores es un espacio de celebraciones en Oviedo. Su equipo comparte las posibilidades de la finca y sus servicios para bodas.',url:'https://www.deloyalatores.com/'},
  {id:'palacio-cutre',name:'Palacio de Cutre',category:'Espacios',zone:'Oriente',place:'Piloña · Oriente',symbol:'♜',summary:'Palacio y finca con vistas a los Picos de Europa para bodas y eventos.',detail:'El Palacio de Cutre presenta un espacio para bodas dentro de su finca en el oriente asturiano. Consulta directamente formatos, capacidad y alojamiento.',url:'https://palaciodecutre.com/eventos/'},
  {id:'capile',name:'Capilé',category:'Catering',zone:'Oviedo',place:'Oviedo · servicio en Asturias',symbol:'◒',summary:'Catering asturiano para bodas y celebraciones con propuestas gastronómicas propias.',detail:'Capilé ofrece catering para bodas y otros eventos desde Oviedo. Puedes consultar menús y servicios actuales en su web.',url:'https://www.capile.com/'},
  {id:'perfday',name:'Perfday Wedding',category:'Wedding planner',zone:'Asturias',place:'Asturias',symbol:'✳',summary:'Diseño, organización y acompañamiento integral para bodas en Asturias.',detail:'Perfday trabaja en la planificación y diseño de bodas en Asturias, desde las primeras decisiones hasta la coordinación del día.',url:'https://www.perfday.es/'},
  {id:'mynoah',name:'My Noah Candy',category:'Wedding planner',zone:'Asturias',place:'Asturias',symbol:'✿',summary:'Planificación de bodas con atención al diseño, flores y coordinación de proveedores.',detail:'My Noah Candy presenta servicios de organización y diseño de bodas en Asturias. Su web explica su enfoque y vías de contacto.',url:'https://www.mynoahcandy.com/'},
  {id:'boda-flores',name:'Boda y Flores',category:'Decoración',zone:'Asturias',place:'Asturias',symbol:'❀',summary:'Decoración personalizada para bodas y otros eventos en Asturias.',detail:'Boda y Flores muestra propuestas decorativas con flores y globos. Consulta ideas y presupuestos en su web.',url:'https://bodayflores.com/'},
  {id:'petit-grinza',name:'Petit Grinza',category:'Decoración',zone:'Asturias',place:'Asturias',symbol:'❁',summary:'Diseño y decoración de bodas con selección de materiales y flores.',detail:'Petit Grinza ofrece diseño y decoración de bodas en Asturias. Su propuesta incluye dirección estética y colaboración con otros especialistas.',url:'https://www.petitgrinza.com/dise%C3%B1o'},
  {id:'videodance',name:'Videodance',category:'DJ y música',zone:'Asturias',place:'Asturias',symbol:'♫',summary:'DJ para bodas con montajes de música, sonido e iluminación.',detail:'Videodance presenta un servicio de DJ para bodas en Asturias con personalización de música, iluminación y puesta en escena.',url:'https://videodance.es/dj/'},
  {id:'pronorte',name:'Pronorte',category:'Sonido e iluminación',zone:'Asturias',place:'Asturias',symbol:'◈',summary:'Servicios técnicos y alquiler de sonido e iluminación para eventos.',detail:'Pronorte es una empresa asturiana de servicios técnicos para eventos. Consulta con su equipo las necesidades de sonido e iluminación de tu boda.',url:'https://www.pronortesonido.es/'}
];
